   </div>
  </div>
 </div>
 <div id='fband'>
  <div class='wrapper'>
   <div id='footer'>
    <p>h&auml;ng was created to help people discover the good of Luxembourg and show what needs to be changed.</p>
	<p>We are not trying to sell Luxembourg, just make it a more enjoyable place through knowledge of what Luxembourg offers and activism to improve it.</p>
	<p>We also want to have a little fun.</p>
   </div>
  </div>
 </div>
</body>
</html>