<!doctype html>
<html>
<head>
 <title>hang - Luxembourg's Zine</title>
 <link href="css/hanged.css" type="text/css" rel="stylesheet">
 <script src="../js/jquery-1.5.2.min.js"></script>
</head>
<body>
 <div id='hband'>
  <div class='wrapper'>
   <div id='header'>
    <a href='../'><img src='../imgs/hanglogosm.png'></a>
	<div id='statement'>Editor area</div>
	<div id='navigation'><ul>
	 <a href='<?php echo $_SERVER['PHP_SELF'] ?>?page=upload'><li>Upload page</li></a>
	 <a href='<?php echo $_SERVER['PHP_SELF'] ?>'><li>Edit zine</li></a>
	</ul></div>
   </div>
  </div>
 </div>
 <div id='cband'>
  <div class='wrapper'>
   <div id='content'>
